# Generated by Django 6.0.3 on 2026-07-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stuid', models.IntegerField()),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('result', models.CharField()),
            ],
        ),
    ]
